### ISSUE TITLE
设置 isTranslucent  为 false 时导航栏透明失效

### ISSUE THREAD

**Issue by shengwanlin** [EnderTan/ETNavBarTransparentDemo#34]
iOS 12.3

在 app 启动时设置
    UINavigationBar.appearance().barTintColor = color
    UINavigationBar.appearance().tintColor = color
    UINavigationBar.appearance().titleTextAttributes =  ...
    UINavigationBar.appearance().isTranslucent = false   //不使用半透明

ViewController中设置
    self.navBarBgAlpha = 0
    self.navBarTintColor = .white

导航栏并没有变透明

**Comment by guojingjingghost** [comment]
我的也是这样的，不知道是不是作者故意这样的

**Comment by EnderTan** [comment]
当导航栏isTranslucent设置为false时，view的默认顶部约束是在导航下方的。所以导航栏已经透明了，但导航栏的后方并没有内容显示，造成你的错觉。
你可以手动布局view，让他布满整个屏幕，或者设置
```
view.clipsToBounds = false
tableView.clipsToBounds = false
```
